// <auto-generated />
namespace EnglishSchool.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class db35 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(db35));
        
        string IMigrationMetadata.Id
        {
            get { return "202105301054153_db35"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
