// <auto-generated />
namespace EnglishSchool.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class db123 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(db123));
        
        string IMigrationMetadata.Id
        {
            get { return "202104190606090_db123"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
